### ISSUE TITLE
Setting additional release properties

### ISSUE THREAD

**Issue by ebabani** [pivotal-cf-experimental/pivnet-resource#12]
Hi,

We would like to be able to set some additional release properties through the pivnet resource when we create a new release. 

According to the pivnet api we should be able to set the following: 

```
    "version": "1.0.0.1",
    "release_notes_url": "http://example.com/release",
    "description": "Release description",
    "release_date": "2013-12-11",
    "release_type": "Security Release",
    "availability": "Admins Only",
    "eula": {
      "slug": "pivotal_software_eula"
    },
    "oss_compliant": "confirm",
    "end_of_support_date": "2015-5-10",
    "end_of_guidance_date": "2015-6-30",
    "end_of_availability_date": "2015-7-4",
    "eccn": "5D002",
    "license_exception": "ENC Unrestricted",
    "controlled": true
```

The resource supports most of these already but we're missing eccn, license_exception, the end dates and oss compliance fields.

**Comment by robdimsdale** [comment]
@ebabani yes this is fine. To clarify we're looking to add the following:

```
controlled: <boolean>
eccn: <string>
license_exception: <string>
end_of_support_date: <string>
end_of_guidance_date: <string>
end_of_availability_date: <string>
```

The question then becomes what is the best API for introducing these fields. Currently we support reading the existing supported fields from individual files (e.g. `version_file`, `description_file`). This approach has found favor with existing users of the pivnet resource, as it is simple; in many cases these files already exist so no additional processing is necessary. It also avoids requiring more yaml, which is generally considered a pleasant relief for many developers.

However, this approach doesn't scale as well or as elegantly as defining them in a structured (read: yaml) `metadata` file. I prefer the idea of parsing a configuration file rather than reading data from multiple disparate files on the filesystem. This approach introduces more yaml into the ecosystem, and more importantly, requires that users of the pivnet resource perform additional processing before they create a release with the pivnet resource.

What are your thoughts on files vs metadata.

Also, @mfine30, @zachgersh as users of the pivnet resource who create products, what are your opinions on configuration via files vs a single, yaml `metadata` file?

Thanks,
Rob

**Comment by zachgersh** [comment]
@robdimsdale 100% agree. If we are going to go down the path of adding even more fields then we should standardize now on some sort of `metadata

**Comment by ebabani** [comment]
Agree with @zachgersh , a metadata file would be my preferred solution as well.

**Comment by mfine30** [comment]
For us, in the short term, the single `metadata` file is more work as most of our configuration is static. That being said, if we want to add more configuration and make it more dynamic in the future, the `metadata` file seems like the more extensible and better approach for a larger user base.

**Comment by robdimsdale** [comment]
Great thanks for the feedback. We will proceed with the `metadata` file as the preferred source of configuration - deprecating (but not removing) the existing fields and adding them as options in the `metadata` file.

Once the relevant stories are created I will link to them here.

Thanks,
Rob

**Comment by robdimsdale** [comment]
The following stories have been created:

- [pivnet resource out should be able to be entirely configured by metadata file](https://www.pivotaltracker.com/story/show/115377541)
- [pivnet resource out should support all metadata values that the API declares are configurable](https://www.pivotaltracker.com/story/show/115377615)

I'll close this issue now; please feel free to open another one with further thoughts or questions.

Thanks,
Rob
