### ISSUE TITLE
Pivnet resource out should allow me to specify an ECCN

### ISSUE THREAD

**Issue by mfine30** [pivotal-cf-experimental/pivnet-resource#14]
Currently, the PivNet API allows me to specify an `ECCN` as a key in the `releases` hash when posting a new release. How do I do this with the PivNet resource? This is required to specify a unique/custom eccn for my p-mysql tile.

Thanks,
Morgan && Frank

**Comment by robdimsdale** [comment]
@mfine30 I think this is covered by https://github.com/pivotal-cf-experimental/pivnet-resource/issues/12 and the corresponding tracker story:

[pivnet resource out should support all metadata values that the API declares are configurable](https://www.pivotaltracker.com/story/show/115377615)

If you think there's more to this, let me know. Otherwise I'll go ahead and close this issue.

Thanks,
Rob

**Comment by mfine30** [comment]
Thanks, @robdimsdale. 

I believe that covers this use case. We have found another interesting case, where we need the ability to specify a Docs Url. Currently, before posting our product to PivNet, we make a (post)[https://network.pivotal.io/docs/api#public/docs/api/v2/product_files.md] to `api/v2/product_files`  so that we can specify custom information, such as file_version, docs_url, and system_requirements. Since this falls into a new endpoint, `product_files`, please let me know if you want me to create a separate issue or this one is ok.

Thanks,
Morgan

**Comment by robdimsdale** [comment]
@mfine30 it'll be easier to track if you open a new issue. I know you referenced this a little in #15 too, but a standalone issue will be easier to discuss and prioritize.

As #12 covers this issue, I'll close it now.

Thanks,
Rob
