### ISSUE TITLE
Pivnet resource out should allow me to specify upgrade paths

### ISSUE THREAD

**Issue by mfine30** [pivotal-cf-experimental/pivnet-resource#15]
Currently, I make several posts to `api/v2/products/p-mysql/releases/<RELEASE_ID>/add_upgrade_path` to tell PivNet what previous versions of my product may be upgraded to this version. I want to be able to provide an array of previous versions of my product, in a file, and the PivNet resource should construct these upgrade paths on PivNet as part of the out.

Thanks,
Morgan && Frank

**Comment by zachgersh** [comment]
@mfine30 this is interesting. Do we also try to put this into the metadata file that we are keeping track of?  We are currently trending toward putting all this data in one spot but maybe this should be configuration via params instead.

**Comment by mfine30** [comment]
@zachgersh correct me if I'm wrong, but so far it seems like all of the metadata information and fields that the PivNet resource has learned about are in regards to making a post to the `releases` endpoint. That is to say it accepts, or will [accept soon](https://www.pivotaltracker.com/story/show/115377615) all metadata values specified at [`/api/v2/products/:product_slug/releases`](https://network.pivotal.io/docs/api#public/docs/api/v2/releases.md)
```json
{
  "release": {
    "version": "1.0.0.1",
    "release_notes_url": "http://example.com/release",
    "description": "Release description",
    "release_date": "2013-12-11",
    "release_type": "Security Release",
    "availability": "Admins Only",
    "eula": {
      "slug": "pivotal_software_eula"
    },
    "oss_compliant": "confirm",
    "end_of_support_date": "2015-5-10",
    "end_of_guidance_date": "2015-6-30",
    "end_of_availability_date": "2015-7-4",
    "eccn": "5D002",
    "license_exception": "ENC Unrestricted",
    "controlled": true
  }
}
```

I am all in favor of this, and it is logical to continue with the stories and ideas discussed in #12. However, the metadata that I am discussing here, namely [`upgrade_paths`](/api/v2/products/:product_id/releases/:release_id/upgrade_paths), is not part of the `releases` hash, but its own thing. Similarly, neither is the `docs_url` that I alluded to in #14, which is part of [`product_files`](https://network.pivotal.io/docs/api#public/docs/api/v2/product_files.md). 

 Perhaps the single metadata file will instead now have many top level keys for the different parts of the overall metadata? 
```yaml
release:
  version: foo
  eccn: some-eccn
  #etc ....
product_files:
  docs_url: http://foo.example.com
release_upgrade_paths:
  versions: 
    - 1.6
    - 1.7
```

Or is it better to split each section up into a separate file whose location is configured via a param?
```yaml
put: pivnet-thingy
  params:
    metadata_file_path: some-path
    product_files_file_path: another-path
    upgrade_file_path: yet-another-path
```

**Comment by robdimsdale** [comment]
@mfine30 @zachgersh I think there should be exactly one metadata file, and it will have multiple top-level keys (this was discussed in the conversation around adding `dependent_products` in https://github.com/pivotal-cf-experimental/pivnet-resource/issues/8) so it looks like we should add another top-level field for these upgrade paths.

I'm not quite sure what this should look like yet, and while I think that the proposed structure of:

```
release_upgrade_paths:
  versions: 
    - 1.6
    - 1.7
```

makes sense, I'm wondering if there's a better way we can lay this out. For example, if the only key under `release_upgrade_paths` is `versions` maybe we don't need both keys?

Do you think there will be additional keys under `release_upgrade_paths`? Do you have other thoughts on the naming of the config?

Thanks,
Rob

**Comment by mfine30** [comment]
@robdimsdale I agree with the single metadata file approach. Looking a little more at the `release_upgrade_paths` endpoint on PivNet, it looks like it is a hash with a pretty simple structure. Since that seems to be the only thing that can go in a `PATCH` to the release_upgrade_paths endpoint, I would agree that a single top level key for an array of upgradable-from versions is acceptable. 
```json
{
  "upgrade_path": {
    "release_id": 45
  }
}
```

**Comment by zachgersh** [comment]
just to fully tease out the design that we seem to be converging on i'd like to propose we go with something that look like the below.

```yaml
release:
  version: foo
  eccn: some-eccn
  eula: some-slug
product_files:
  docs_url: http://foo.example.com
release_upgrade_path_ids:
  - 45
  - 25
```

I would love to avoid too many nested keys as it makes it both harder to parse on the pivnet-resource end and more complex for our end users to put together.  Does this make sense?

As an alternate approach, what if we switched from taking yaml to taking json that is identical to what each of these pivnet endpoint takes (just for the optional fields though)? I actually like this approach better as you get something that is less surprising to user and it give them the ability to copy/paste straight from the pivnet API docs. Removing an intermediate format before this data eventually gets turned into json seems like a good idea to me.

```son
{
  "release": {
    "version": "1.0.0.1",
    "release_notes_url": "http://example.com/release",
    "description": "Release description",
    "release_date": "2013-12-11",
    "release_type": "Security Release",
    "availability": "Admins Only",
    "eula": {
      "slug": "pivotal_software_eula"
    },
    "oss_compliant": "confirm",
    "end_of_support_date": "2015-5-10",
    "end_of_guidance_date": "2015-6-30",
    "end_of_availability_date": "2015-7-4",
    "eccn": "5D002",
    "license_exception": "ENC Unrestricted",
    "controlled": true
  },
 "upgrade_paths": {
    "release_id": 45
  },
  "product_files": []
  }
}
```

**Comment by mfine30** [comment]
@zachgersh I definitely am a fan of the simpler mapping between the pivnet API docs and the file that the PivNet resource expects. Also worth mentioning that since JSON already is YAML, I think the user should have their choice. In any case, this seems like a great approach for the `release` part of the hash. I'm less certain about it for the `product_files` hash and have stronger concerns about the upgrade_paths.

The `product_files` hash is rather large and potentially confusing. The `product_files` hash from the PivNet docs is the following:
```
{
  "product_file": {
    "aws_object_key": "product_files_test/product-16/pcf-1.1.0.0.ova",
    "description": "OVA Release of Pivotal CF v1.1.0.0",
    "docs_url": "http://zombo.com",
    "file_type": "Software",
    "file_version": "1.1.0.0",
    "included_files": [
      "pcf-server.exe",
      "pcf-client.exe"
    ],
    "md5": "cb0781c2acb239865c90b76d4098f354",
    "name": "Pivotal CF",
    "platforms": [
      "Android",
      "AWS",
      "Apt-Get"
    ],
    "released_at": "2015/12/31",
    "system_requirements": [
      "Windows Vista",
      "Microsoft Office 1995"
    ]
  }
}
```
How many of those keys does the concourse user actually care about and how many of them the PivNet resource will generate for us is still unclear to me. 

As for the `upgrade_paths`, I strongly argue that the concourse user should in no way need to know about the `release_ids` of previous releases. Instead, as a user of the PivNet resource, I would like to declare previous `release_versions` that can be upgraded from, i.e. the semantic versions that I am accustomed to using with my product, not the unique IDs that PivNet assigns to them. That is to say, I would like my hash, for the upgradeable from versions, to look like:
```
{
  "release_upgrade_paths": [1.5.9, 1.5.10, 1.6.2, 1.6.4, 1.8.0.beta.2]
}
```

**Comment by zachgersh** [comment]
@mfine30 - I totally agree and like the idea of `release_id` being abstracted away from the user. I will totally use that suggestion when implementing this.

I am going to move forward with implementing the agreed upon structure which can be boiled down to:

```yaml
top_level_endpoint_name:
  endpoint_field: endpoint_data
 ```

Any endpoint that takes multiples of a particular type (like `product_files` for instance) will take an array of those items.

Does this sound good @mfine30 / @robdimsdale?

**Comment by robdimsdale** [comment]
Thanks for all this, it sounds like we're broadly on the same page. Apologies to @mfine30 for hijacking this original question; I've created the following story to capture the original requirement:

- [pivnet resource out should support automatically setting upgrade paths](https://www.pivotaltracker.com/story/show/116499247)

Agreed with both @mfine30 and @zachgersh that we gain a lot by basing our configuration file on the existing pivnet API. Firstly, as we've identified, JSON is valid YAML, so if our metadata looks similar to Pivnet this probably facilitates construction of the metadata. Secondly, I would expect that the more similar the structure between the pivnet API and the metadata file, the less cognitive overhead will experience. However, I also expect there will be some fundamental differences between them, otherwise the incremental value added to the end-user's experience by the pivnet resource is diminished; it may as well be `curl`.

To dive into some specific questions:

_How much of the `product_files` should be mandatory, how much should be optional, and how much should not be configurable at all by the end-user?_

Not all of this is known at this point as some of it depends on future use-cases. However, things that are definitely **not configurable** include: `aws_object_key` (as we determine this from the `bucket_name` and optionally the `upload_as` field) and `md5` as we calculate that ourselves. Some of the other things like `platform` and `docs_url` aren't supported yet, but I see no reason they cannot be optionally-configurable in the future.

_Should the `upgrade_paths` look like the pivnet endpoint (i.e. IDs) or expose a higher-level of abstraction?_

My gut feeling is that an array of semantic versions is more user-friendly than an array of IDs, because it's fewer things the end-user must discover, and the intention of the pivnet resource is to put common operations like discovery of release IDs in a single, well-tested place. However, I haven't thought about this too much, so there may be good arguments against this structure.

_Should the release fields love under a top-level `release` key or should they all be top-level keys?_

I think nesting them under the `release` key makes sense. It's a little odd because everything pertains to the release, so the top-level key feels unnecessary, but I think it's probably cleaner to keep it. Happy to hear arguments either way though.

If there are no further thoughts or questions I will close this issue.

Thanks,
Rob

**Comment by zachgersh** [comment]
Thanks Rob! I think I have enough to continue development. @mfine30
anything else to add?

**Comment by mfine30** [comment]
That sounds great @robdimsdale. My one comment is perhaps a clarification on the top-level `release` key. I don't think that there should be a single top-level `release` key that everything is a child of. Instead, `release` should be a parent to the potential children values it can support per the PivNet API. That may be what you intended in your comment as well, just want to clarify. 

```yaml
release:
  eula:
  availability:
  etc...
product_files:
  docs_url:
upgrade_paths: []
```

**Comment by robdimsdale** [comment]
@mfine30 yes thanks for the clarification - what you describe is what I had intended.

**Comment by robdimsdale** [comment]
Sounds like the aforementioned story captures the request in this issue, and we're all on the same page as to the implementation of the metadata file, so I'll close this issue now.

Thanks,
Rob
