### ISSUE TITLE
I should be able to fetch product dependencies

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [pivotal-cf-experimental/pivnet-resource#9]
If a product depends on a particular version of a stemcell, for example, I should be able to fetch that stemcell from the resource configured for that product.

If this is not feasible then I should be able to fetch enough dependency metadata to configure additional resources

**Comment by zachgersh** [comment]
So @robdimsdale which way are we leaning? I feel like I am more on the side of just downloading the metadata required to make the product work instead of "magically" grabbing a stem cell you require. Seems like the most understandable approach?

**Comment by robdimsdale** [comment]
@xtreme-gavin-enns I don't think blindly downloading all dependencies is a good idea in the general case (think of how many product have dependencies on elastic runtime which is around 3.5GB).

I would like to start by writing this information to a file, and probably also to the returned metadata that gets rendered in the concourse UI.

Just to be clear, we're talking about providing the following information:

```
dependent_products:
- name: stemcells
  version: 3160.1
- name: elastic-runtime
  version: 1.6.2
```

I expect we will write this information to a metadata file, probably located at `/tmp/build/get/metadata` - currently we write out the `version` file by itself to `/tmp/build/get/version` but I would prefer to use a more structured file format such as YAML for this dependency information.

The metadata returned to the concourse via stdout (the stuff that ultimately gets rendered to the UI) will be JSON.

Do you think this proposal is a good place to start? Does it meet your immediate requirements of discoverability of dependencies? If not we can broaden the conversation to include some mechanism to optionally download dependencies (potentially recursively).

Thanks,
Rob

**Comment by xtreme-gavin-enns** [comment]
That definitely helps. But It means that we have to fetch a product, inspect the metadata, then either manually (in a task) download the dependencies or script the configuration of the target pipeline.

**Comment by robdimsdale** [comment]
@xtreme-gavin-enns I hear that. Even though the product dependencies of a given product are (relatively) static, the versions of them are not, and so you'd have to dynamically reconfigure a pipeline with a new resource and version in order to access the dependencies.

A few things I'm concerned about with automatically downloading dependencies are:
- if your dependencies are large, the `get` step will take a long time and currently doesn't have great out (we have a stories around improving visibility into upload/download progress). This is especially annoying if you didn't mean to configure the resource to download your dependencies.
- Should we expose the ability to choose which dependencies you want (e.g. I want all the files from dependency A, nothing from B and things that match globs from C)? This would require knowing ahead of time what your dependencies are, which doesn't feel great. The interface here also seems potentially complex.
- handling recursive dependencies seems like it will significantly increase the complexity.

To that end, I would propose the following solution for a first attempt at solving this problem:
- start by writing the product dependencies (and their versions) to a file, and return to the UI
 - this is a relatively cheap way of ensuring we're on the right path before we invest effort into downloading files of dependencies.
- add a boolean flag to the config called something like `download_product_dependencies: true` which defaults to false to avoid unexpected behavior.
- when this flag is configured to true for a resource, we will download all the files for all the immediate dependencies (no filtering, no recursion) into a directory hierarchy on the file system of the container, structure TBD.

At a high level, how does that sound?

**Comment by xtreme-gavin-enns** [comment]
That sounds really reasonable

**Comment by robdimsdale** [comment]
Great thanks @xtreme-gavin-enns 

I've created the following stories in our tracker to capture the initial set of work (emitting and saving the metadata):

- [pivnet resource in should write metadata file](https://www.pivotaltracker.com/story/show/115217361)
- [pivnet resource in should write dependent product release information to metadata file ](https://www.pivotaltracker.com/story/show/115217519)
- [pivnet resource in should emit metadata about dependent products to stdout](https://www.pivotaltracker.com/story/show/115217581)

once we're happy we've on the path to solving the right problem, we can tackle the following story to download the files themselves:

- [pivnet resource in should optionally download all files of all dependent products](https://www.pivotaltracker.com/story/show/115217791)

I'll close this issue now, but feel free to open another if you think we've missed anything or if you have further thoughts or questions.

Thanks,
Rob

**Comment by robdimsdale** [comment]
@xtreme-gavin-enns the more I think about downloading dependencies the more uncomfortable I feel about it. We've been writing the metadata for some time now, how has that been going? Do you think you still need the downloads of dependent products? How would you feel if we ended up not implementing that feature?

**Comment by xtreme-gavin-enns** [comment]
@robdimsdale I'm not working with the pivnet resource anymore. I think this issue was mostly motivated by attempts to fully automate platform updates. Current project is running entirely on pcfdev and pws so we avoid these problems. For most teams hard-coding versions (for dependencies) in pipelines is fine though.

**Comment by robdimsdale** [comment]
Per the above conversation, the cost for the final story above ([pivnet resource in should optionally download all files of all dependent products](https://www.pivotaltracker.com/story/show/115217791)) is not worth the gain at this time, so we won't implement it
